
name: Train and Deploy Faces Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Especifica una versión concreta
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip
        
    - name: Install Python dependencies
      run: |
        pip uninstall tensorflow -y  # Elimina cualquier instalación previa
        pip install tensorflow-cpu==2.10.0  # Especifica versión compatible
        pip install -r requirements.txt
        
    - name: Download dataset from Google Drive
      run: |
        pip install gdown  # Asegúrate de que gdown esté instalado
        gdown --id 1SkLkI8bY-2Hw9Cthq2T8hoUwaODdIrb7
        tar -xzvf flowers299.tgz
        
    - name: Execute model training with CPU-only
      run: |
        python -c "import tensorflow as tf; print('TF está usando GPU:', tf.config.list_physical_devices('GPU'))"
        python faces_model.py
        
    - name: Show directory structure
      run: |
        ls -la
        ls -R
        
    - name: Docker setup
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MODEL_NAME: ${{ secrets.MODEL_NAME }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker run -d --name serving_base tensorflow/serving
        docker cp $MODEL_NAME serving_base:/models/$MODEL_NAME
        docker commit --change "ENV MODEL_NAME $MODEL_NAME" serving_base $DOCKER_USER/tensorflow-$MODEL_NAME:${{ github.sha }}
        docker push $DOCKER_USER/tensorflow-$MODEL_NAME:${{ github.sha }}
